GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/6419e6cabd2fc6ca40347533

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "new test record",
  "author": "Michael Cain",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "author": "Missing Title",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "url missing",
  "author": "Michael Cain",
  "likes": 7
}
